Add multiple NIC/bridge support in a portable way
Commit adds support for multiple NIC/bridges in a portable way. However,
everything comes at some cost:

  * all KVM_NETWORK_ -> KVM_NETWORKx_ where 'x' is a number
  * KVM_BRIDGE -> KVM_BRIDGEx, KVM_BRIDGE_OPT -> KVM_BRIDGEx_OPT
  * KVM_MACADDRESS is no longer supported
  * KVM_MACADDRESS is replaced by KVM_NETWORKx_MACADDR
  * parse_network() added

Symlinks to 'kvm-ifup', resp. 'kvm-ifdown', will be created in 'net/' directory
per each running VM with following convention: '$VM_NAME-$BR_NUM-ifup'. These
should be removed (automatically) after VM is shut down.

Signed-off-by: Zdenek Styblik <stybla@turnovfree.net>

diff --git a/net/kvm-ifup b/net/kvm-ifup
--- a/net/kvm-ifup
+++ b/net/kvm-ifup
@@ -1,10 +1,61 @@
 #!/bin/sh
-#
-# Script called by kvm on tap interface creation
-#
+# Script called by kvm after tap interface is created
+set -e
+set -u
+TAP=${1:-''}
+if [ -z "$TAP" ]; then
+	printf "No TAP interface given.\n" 1>&2
+	exit 1
+fi
+PREFIX=""
+if [ "$(dirname -- "$0")" = "." ]; then
+	PREFIX="."
+fi
 
+KVM_BR_NUM=$(basename -- "$0" "-ifup" |\
+	awk '{ arr_len=split($1, arr, "-"); print arr[arr_len]; }')
+if [ -z "$KVM_BR_NUM" ]; then
+	printf "Failed to parse out 'KVM_BR_NUM'.\n" 1>&2
+	exit 1
+fi
+
+VM_NAME=$(basename -- "$0" "-${KVM_BR_NUM}-ifup")
+if [ -z "$VM_NAME" ]; then
+	printf "Failed to parse out VM_NAME.\n" 1>&2
+	exit 1
+fi
+
+VM_DESCRIPTOR="$(dirname -- "$0" | sed 's@net$@@')${PREFIX}/vm/${VM_NAME}-vm"
+if [ ! -e "$VM_DESCRIPTOR" ]; then
+	printf "VM config '%s' doesn't exist.\n" "$VM_DESCRIPTOR" 1>&2
+	exit 1
+fi
+
+NET_TYPE=$(grep -E -e  "^KVM_NETWORK${KVM_BR_NUM}_TYPE=" "$VM_DESCRIPTOR" | \
+	awk -F'"' '{ print $2 }')
+KVM_BRIDGE=$(grep -E -e "^KVM_BRIDGE${KVM_BR_NUM}=" "${VM_DESCRIPTOR}" | \
+	awk -F'"' '{ print $2 }')
 printf -- "%s:\n" "${0}"
-printf "Adding %s to bridge interface %s\n" "${1}" "${KVM_BRIDGE}"
-brctl addif "${KVM_BRIDGE}" "${1}"
-ip link set "${1}" up
-
+if [ "$NET_TYPE" = "ovs" ]; then
+	if [ -z "$KVM_BRIDGE" ]; then
+		printf "Failed to parse 'KVM_BRIDGE${KVM_BR_NUM}'\n" 1>&2
+		exit 1
+	fi
+	KVM_BRIDGE_OPT=$(grep -E -e "^KVM_BRIDGE${KVM_BR_NUM}_OPT=" \
+		"${VM_DESCRIPTOR}" | awk -F'"' '{ print $2 }')
+	printf "Adding %s to bridge interface %s with opt '%s'\n" \
+		"${TAP}" "${KVM_BRIDGE}" "${KVM_BRIDGE_OPT}"
+	if [ -z "${KVM_BRIDGE_OPT}" ]; then
+		ovs-vsctl add-port "${KVM_BRIDGE}" "${TAP}"
+	else
+		ovs-vsctl add-port "${KVM_BRIDGE}" \
+			"${TAP}" ${KVM_BRIDGE_OPT:-''}
+	fi
+else
+	if [ -z "$KVM_BRIDGE" ]; then
+		KVM_BRIDGE="kvmnat"
+	fi
+	printf "Adding %s to bridge interface %s\n" "${1}" "${KVM_BRIDGE}"
+	brctl addif "${KVM_BRIDGE}" "${1}"
+fi
+ip link set "${TAP}" up
